config/routes.rb
SiteSmsalvaVidas::Application.routes.draw do
  get "index" => "home#index"
  get "como_funciona" => "home#como_funciona"
  get "o_projeto" => "home#o_projeto"
  get "download" => "home#download"
  get "documentacao" => "home#documentacao"
  get "cronograma" => "home#cronograma"

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def como_funciona
  end
  
  def o_projeto
  end
  
  def download
  end
  
  def documentacao
  end
  
  def cronograma
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/como_funciona.html.erb
<div class="post">
	<h2 class="title">
		Como funciona?
	</h2>
	<div class="entry">
		<div id="passo_1" class="passo">
			<h1>Passo 1</h1>
			<p>Os operadores da defesa civil cadastram as áreas de risco usando usando o SMSalva-vidas com um mapa</p>
			<div id="img_como_funciona_1" class="img_como_funciona">
				<%= image_tag "mapeando_area.png" %>
			</div>
		</div>
		<br style="clear: both"/>
		
		<div id="passo_2" class="passo">
			<h1>Passo 2</h1>
			<p>Os moradores de áreas de risco são cadastrados utilizando um mapa para localização.</p>
			<div id="img_como_funciona_2" class="img_como_funciona">
				<%= image_tag "cadastrando_morador.png" %>
			</div>
		</div>
		<br style="clear: both"/>
		
		<div id="passo_3" class="passo">
			<h1>Passo 3</h1>
			<p>Os operadores da defesa civil, ao perceberem uma possível catástofre(como chuvas, por exemplo), manda o SMSalva-vidas enviar SMS para as pessoas localizadas naquela região.</p>
			<div id="img_como_funciona_3" class="img_como_funciona">
				<%= image_tag "avisando_sms.png" %>
			</div>
		</div>
		<br style="clear: both"/>
	</div>
</div>

app/views/home/cronograma.html.erb
<div class="post">
	<h2 class="title">
		Cronograma de desenvolvimento
	</h2>
	
	<div class="entry">
		<%= image_tag 'logo_STI.png', :width => '300', :style=>"float: right" %>
		<br/>
		O desenvolvimento do projeto conta com uma comunidade aberta e atualmente é mantido por um grupo de profissionais da <a href="http://www.sti.uff.br">Superintendência de Tecnologia da Informação - STI</a> da <a href="http://www.uff.br">Universidade Federal Fluminense</a>.
	</div>
	
	<div class="entry">
		<h3>Versão 0.1 - Prevista para Novembro/2011</h3>
		<ul>
			<li>Definição da estrutura básica do projeto (site, documentação, listas, repositórios, etc)</li>
			<li>Definição e implementação do layout básico da aplicação</li>
			<li>Desenvolvimento do <span class="destaque3">Gerenciamento de cidades</span></li>
			<li>Desenvolvimento do <span class="destaque3">Gerenciamento de usuários</span></li>
		</ul>
	</div>
	
	<div class="entry">
		<h3>Versão 0.2 - Prevista para Dezembro/2011</h3>
		<ul>
			<li>Desenvolvimento do <span class="destaque3">Gerenciamento de habitantes</span> com cadastro via interface web</li>
			<li>Desenvolvimento do <span class="destaque3">Gerenciamento de profissionais de apoio</span></li>
			<li>Desenvolvimento do <span class="destaque3">Gerenciamento de equipes de apoio</span></li>
		</ul>
	</div>
	
	<div class="entry">
		<h3>Versão 1.0 - Prevista para Janeiro/2012</h3>
		<ul>
			<li>Desenvolvimento do <span class="destaque3">Gerenciamento de áreas de risco</span></li>
			<li>Desenvolvimento do <span class="destaque3">Gerenciamento de notificações</span></li>
		</ul>
	</div>
	
	<div class="entry">
		<h3>Versão 1.1 - Prevista para Março/2012</h3>
		<ul>
			<li>Desenvolvimento do <span class="destaque3">Visualização pública de áreas de risco</span></li>
			<li>Desenvolvimento do <span class="destaque3">Verificação de notificações para área</span></li>
			<li>Desenvolvimento do <span class="destaque3">Visualização de posicionamento GPS em áreas de risco</span> (Android)</li>
			<li>Desenvolvimento do <span class="destaque3">Cadastro de habitantes usando um celular</span> (Android)</li>
		</ul>
	</div>
	

</div>

app/views/home/documentacao.html.erb
<div class="post">
	<h2 class="title">
		Instalação
	</h2>
	<div class="entry">
	    <p>
	    	<%= link_to 'Faça o Download da versão estável', download_path %> e prossiga com a instalação do Ruby on Rails e MySQL.
	    </p>
	</div>
	<div class="entry">
		<p>
			<%= image_tag 'ruby_on_rails_logo.jpg', :width => '100' %>
			<br/>
			<span class="destaque3">Ruby on Rails</span>: instalação de Ruby (em breve), instalação de Ruby on Rails(em breve), configuração de Gateway SMS(em breve)
		</p>
	</div>
	<div class="entry">
		<p>
			<%= image_tag 'logo-mysql-300x218.jpg', :width => '100' %>
			<br/>
			<span class="destaque3">Banco de dados MySQL</span>: instalação de MySQL(em breve)
		</p>
	</div>
</div>

<div class="post">
	<h2 class="title">
		Visão geral
	</h2>
	<div class="entry">
		<p>A solução é segmentada por <span class="destaque">cidades brasileiras</span>, ou seja, cada usuário possui uma cidade e cada cidade possui um conjunto de habitantes cadastrados. Por definição, cada cidade só pode controlar o seu próprio conjunto de habitantes e suas áreas de risco.</p>
	</div>
</div>

<div class="post">
	<h2 class="title">
		Glossário
	</h2>
	<div class="entry">
		<ul>
			<li><span class="destaque">Cidade</span>: representa cada cidade brasileira sendo assim um agrupamento lógico das atividades. Por exemplo, a cidade de Niterói/RJ que possui habitantes, áreas de risco, gestores, etc</li>
			<li><span class="destaque">Área de risco</span>: representa uma área de risco de uma cidade. Possui informações geográficas (geolocation) e informações para notificação e classificação de risco</li>
			<li><span class="destaque">Habitante</span>: representa os habitantes de uma cidade, estando ou não localizados em uma área de risco</li>
			<li><span class="destaque">Notificação</span>: representa alguma forma de notificação do SMSalva-vidas aos habitantes(interessados) de uma determinada área. Pode ser difundida através de diversos canais: mensagem SMS, e-mail, mensagem Mobile, twitter, facebook, etc</li>
			<li><span class="destaque">Equipe de apoio</span>: representa uma equipe de apoio de uma cidade a uma determinada área de risco. Pode ser composta por diversos profissionais de apoio.</li>
			<li><span class="destaque">Profissional de apoio</span>: representa um profissional que integra uma equipe de apoio de uma cidade a uma ou mais áreas de risco. Possui o celular cadastrado e não possui acesso ao sistema.</li>
		</ul>
	</div>
</div>

<div class="post">
	<h2 class="title">
		Papéis
	</h2>
	<div class="entry">
		<ul>
			<li><span class="destaque">Administrador</span>: pode executar qualquer atividade em qualquer cidade desejada</li>
			<li><span class="destaque">Gestor de cidade</span>: pode executar qualquer atividade somente na sua cidade</li>
			<li><span class="destaque">Cadastrador de cidade</span>: pode cadastrar novos habitantes na sua cidade</li>
			<li><span class="destaque">Notificador de cidade</span>: pode notificar os habitantes de uma determinada cidade</li>
			<li><span class="destaque">Anônimo</span>: visualiza as áreas filtrando por cidade e quantos habitantes estão em cada uma delas, além de poder visualizar as notificações por cidade</li>
		</ul>
	</div>
</div>

<div class="post">
	<h2 class="title">
		Funcionalidades
	</h2>
	<div class="entry">
		<ul>
			<li><span class="destaque3">Gerenciamento de cidades</span>: visualização, edição e ativação/desativação de cidades do Brasil. Caso exista a necessidade de divulgação no Twitter, deve ser informado o login e senha, assim como para o Facebook. Cada cidade deve estar ligada a um estado brasileiro.</li>
			<li><span class="destaque3">Gerenciamento de usuários</span>: listagem com filtro por cidade, cadastro, edição e ativação/desativação dos usuários. No cadastro deve-se selecionar a cidade e informar se ele é gestor, cadastrador ou notificador daquela cidade. Atributos: nome, login, senha, e-mail e celular.</li>
			<li><span class="destaque3">Gerenciamento de habitantes</span>: listagem com filtro por cidade, cadastro, edição e remoção e desativação de habitantes. No cadastro deve-se selecionar a cidade e informar a localização GPS da sua habitação usando um mapa. Esse cadastro poderá ser realizado através de uma plataforma <span class="destaque2">mobile (Android)</span>.</li>
			<li><span class="destaque3">Gerenciamento de profissionais de apoio</span>: listagem com filtro por cidade e por equipe, cadastro, edição e remoção e desativação de profissionais de apoio (geralmente operadores da defesa civil). Atributos: nome, celular1, celular2, cidade.</li>
			<li><span class="destaque3">Gerenciamento de equipes de apoio</span>: alocação de profissionais de apoio em equipes com o objetivo de dar atenção a uma determinada área em caso de risco de catástrofes. Atributos: nome, profissionais que a compõem, cidade de atuação.</li>
			<li><span class="destaque3">Gerenciamento de áreas de risco</span>: listagem com filtro por cidade, cadastro, edição e remoção e desativação de áreas de risco. Atributos: nome da área, nível de risco (<a href="http://www.cfh.ufsc.br/~gedn/sibraden/cd/EIXO%203_OK/3-37.pdf">referência</a>), cidade, equipes de apoio, mensagens SMS </li>
			<li><span class="destaque3">Gerenciamento de notificações</span>: visualização, detalhamento (confirmação de entrega, no caso de SMSs) e envio de notificações a uma determinada área de risco (localizada em uma cidade). Atributos: texto para habitantes (SMS), texto para equipes (SMS), twittar?, publicar no facebook?</li>
			<li><span class="destaque3">Visualização pública de áreas de risco</span>: visualização pública (no mapa) de áreas de risco filtradas por cidade.</li>
			<li><span class="destaque3">Verificação de notificações para área</span>: capacidade de consultar uma área específica para saber se existe alguma notificação para aquela área.</li>
			<li><span class="destaque3">Visualização de posicionamento GPS em áreas de risco</span>: consultar se uma coordenada GPS está dentro de uma área de risco de alguma cidade. Essa consulta deverá ser realizada em um <span class="destaque2">celular Android</span></li>
		</ul>
	</div>
</div>

app/views/home/download.html.erb
<div class="post">
	<h2 class="title">
		Download
	</h2>
	<div class="entry">
	    Esse é um projeto com código livre, portanto, seu código está disponível no <a href="https://github.com/thiagodiogo/smsalva-vidas">GitHub</a>
	</div>
	<div class="entry">
	    Para fazer a instalação, consulte a <%= link_to 'documentação', documentacao_path %>.
	</div>
</div>

app/views/home/index.html.erb
<div class="post">
	<h2 class="title">
		O que é?
	</h2>
	<div class="entry">
		<p>É uma aplicação web, disponível como Código Livre (open source) sob a licença General Public License (<a href="http://pt.wikipedia.org/wiki/GNU_General_Public_License">GPL</a>) e que pode ser usada para difundir informações durante períodos pré-crise.</p>
		<iframe width="420" height="315" src="http://www.youtube.com/embed/H0YwQFlskuM" frameborder="0" allowfullscreen></iframe>
	</div>
</div>

<div class="post">
	<h2 class="title">
		Qual o objetivo?
	</h2>
	<div class="entry">
		<p>Desenvolver uma solução capaz de ajudar as Prefeituras e Cidades brasileiras a lidarem com desastres naturais através do envio de SMS para habitantes de áreas de risco.</p>
	</div>
</div>

<div class="post">
	<h2 class="title">
		Quando?
	</h2>
	<div class="entry">
		<p>Tem sido concebida desde Julho de 2010, com a construção de um piloto em Novembro de 2010 e agora iniciou-se o seu desenvolvimento de forma aberta. <%= link_to 'Veja mais detalhes do projeto', o_projeto_path %>.</p>
	</div>
</div>

<div class="post">
	<h2 class="title">
		Por que?
	</h2>
	<div class="entry">
		<p>A Tecnologia da Informação (TI) pode (e deve) ajudar a salvar vidas através da utilização de serviços como Short Message Service (SMS) e Cloud Computing, de conceitos como Georreferenciamento e de ferramentas como Ruby on Rails e MySQL. A união desses ingredientes podem resultar em soluções de baixo custo e realmente úteis para a sociedade. <%= link_to 'Veja a documentação do projeto', documentacao_path %></p>
	</div>
</div>

<div class="post">
	<h2 class="title">
		Quem?
	</h2>
	<div class="entry">
		<p>O projeto conta com uma comunidade aberta e atualmente é mantido por um grupo de profissionais da <a href="http://www.sti.uff.br">Superintendência de Tecnologia da Informação - STI</a> da <a href="http://www.uff.br">Universidade Federal Fluminense</a>.</p>
		<p>Atualmente, o principal desenvolvedor é <a href="http://thiagodiogo.blogspot.com">Thiago Diogo</a>.</p>
	</div>
</div>

<div class="post">
	<h2 class="title">
		Participe!
	</h2>
	<div class="entry">
		<p>Discuta conosco na <a href="http://groups.google.com/group/smsalva-vidas-dev/">lista de discussão de desenvolvimento e </a><b>utilize o botão "Sugestões e idéias" à direita</b></p>
	</div>
</div>

app/views/home/o_projeto.html.erb
<div class="post">
	<h2 class="title">
		O projeto
	</h2>
	<div class="entry">
		<%= image_tag 'logo_uff.gif', :width => '220', :style=>"float: right" %>
		<p>
			Chuvas tropicais, mudanças climáticas, desastres ecológicos, situações de emergência. As recentes tragédias ocorridas na Região Serrana, com elevado número de mortos, têm se tornado comuns em outras regiões pelo Brasil. 
		</p>
		<p>
			Apesar das experiências de outros desastres naturais, ainda é comum culpabilizar a natureza pelo número elevado de mortos. Existe no Brasil a mentalidade e o conceito de que Defesa Civil e atenção aos desastres são, basicamente, atuar durante ou depois de o desastre acontecer. 
		</p>
		<p>
			Considerando-se o valor da vida humana e os gastos de atendimento médico-hospitalar e de saúde pública, pouco se vê em relação à ações de prevenção a vida da população, principalmente as de áreas de risco.
		</p>
	</div>
	<div class="entry">
		<p>
			E foi a partir de pesquisas com serviços de mensagens curtas (SMS) para a área de saúde, desenvolvidas por alunos de pós-graduação da UFF e com auxílio de uma empresa incubada, que pesquisadores do Núcleo de Tecnologia da UFF, motivados pelos acontecimentos no morro do Bumba, em Niterói, e na Região Serrana do Rio de Janeiro, criaram o SMSalva-vidas.
		</p>
		<p>
			Este software, que está sendo oferecido gratuitamente ao poder público, tem como objetivo atuar como uma ferramenta integradora de informações e comunicação para os gestores públicos municipais, buscando o melhor gerenciamento de recursos e ações relacionados aos desastres naturais, como execução de planos de trabalho para situações de emergência.
		</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="smsalva-vidas sms geolocation rails" />
	<meta name="description" content="" />
	<title>Projeto SMSalva-vidas</title>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= yield :head %>
</head>
<body>
	<div id="header">
		<h1><a href="<%= root_path %>" ><div id="sms">SMS</div><span>alva-vidas</span></a></h1>
		<h2>Salvando vidas usando SMS</h2>
	</div>
	<div id="page">
		<div id="sidebar">
			<ul>
				<li>
					<h2>o projeto</h2>
					<ul>
						<li><%= link_to 'Home', root_path %></a></li>
						<li><%= link_to 'Como funciona?', como_funciona_path %></a></li>
						<li><%= link_to 'Detalhes do projeto', o_projeto_path %></a></li>
					</ul>
				</li>
				<li>
					<h2>a solução</h2>
					<ul>
						<li><%= link_to 'Documentação', documentacao_path %></li>						
						<!--<li><%= link_to 'Screenshots', "#" %></a></li>-->
						<li><%= link_to 'Download', download_path %></li>
						<li><%= link_to 'Cronograma', cronograma_path %></li>
					</ul>
				</li>
				<li>
					<h2>comunidade</h2>
					<ul>
						<li><%= link_to 'Contribua!', "#" %></a></li>
					</ul>
				</li>
			</ul>
			<div style="clear: both;">&nbsp;</div>
		</div>
		<div id="content">
			<div class="flash">
				<% flash.each do |type, message| -%>
				<div class="flash <%= type %>">
					<p><%= message %></p>
				</div>
				<% end -%>
			</div>
			<div id="main">
				<%= yield %>
			</div>
		</div>
		<div id="footer">
			<p id="links"><%= link_to 'Política de privacidade', "#" %> | <%= link_to 'Termos de uso', "#" %> | <a href="http://validator.w3.org/check/referer" title="This page validates as XHTML 1.0 Transitional"><abbr title="eXtensible HyperText Markup Language">XHTML</abbr></a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="This page validates as CSS"><abbr title="Cascading Style Sheets">CSS</abbr></a></p>
			<p id="legal">Desenvolvido por <a href="http://thiagodiogo.blogspot.com">Thiago Diogo</a> @<%= Time.now.year %></p>
		</div>
	</body>
	<%= yield :js %>
	
	<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-26046991-1']);
	_gaq.push(['_trackPageview']);
	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
		
		var uvOptions = {};
		  (function() {
		    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
		    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/ixh3hRz3YVssgEIRTPVXRA.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
		  })();
	</script>
</html>